# Generated by Django 2.1.5 on 2019-03-07 18:56

from django.db import migrations, models
import vorgang.auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('vorgang_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(default=vorgang.auth.models._make_api_key, max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='api_secret',
            field=models.CharField(default=vorgang.auth.models._make_api_secret, max_length=86),
        ),
    ]
