# Generated by Django 2.1.5 on 2019-03-07 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bureau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(max_length=40)),
                ('credits', models.IntegerField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('not_before', models.DateTimeField(default=django.utils.timezone.now)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agents', models.ManyToManyField(to='bureau.Agent')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repositorty.Category')),
            ],
        ),
    ]
